name: Issue Report
description: File an issue report
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered. If you're unsure whether or not a previous issue matches your own, file a new issue.
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: Are you using any gamescope patches or a forked version of gamescope?
    description: Please confirm any issues occur on upstream gamescope without any patches before filing an issue here.
    options:
    - label: The issue occurs on upstream gamescope without any modifications
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of the issue you're experiencing. If this is a regression, please try to provide the last gamescope version where the issue did not occur for you.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the issue. The clearer the steps, the easier it will be for others to try and help debug it.
    placeholder: |
      1. Launch Dota 2 from Steam with the gamescope launch command `gamescope -f -r 120 -- %command%`...
      2. Enter a bot match
      3. Move the cursor around
  validations:
    required: false
- type: textarea
  attributes:
    label: Hardware Information
    description: |
      examples:
        - **Device type**: Steam Deck, Desktop, Laptop, etc.
        - **Distro**: SteamOS 3.6.15 (`cat /etc/os-release`)
        - **CPU**: 32-core AMD Ryzen Threadripper 7970X (`inxi` or `cat /proc/cpuinfo`)
        - **GPU**: Advanced Micro Devices [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] (`lspci -nn | grep VGA` or `lshw -C display -numeric` or `vulkaninfo --summary | grep deviceName`)
        - **Driver Version**: Mesa 24.3.1 or NVIDIA 565.77 (`vulkaninfo --summary | grep driverInfo` or `nvidia-smi`)
          **FOR NVIDIA**: If you're using an NVIDIA driver, please run `nvidia-bug-report.sh` and attach your `nvidia-bug-report.log.gz` in the bottom section of the form.
    value: |
        - Device type: 
        - Distro: 
        - CPU: 
        - GPU: 
        - Driver Version: 
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Software Information
    description: |
      examples:
        - **Desktop environment**: KDE 6.2.2
        - **Session type**: Wayland (`echo $XDG_SESSION_TYPE`)
        - **Gamescope version**: gamescope version 3.15.15 (gcc 14.2.1) (find this with `gamescope --version`)
        - **Gamescope launch command(s)**: `gamescope -f -h 2160 -w 7680 -r 120 -- %command%`
    value: |
        - Desktop environment: 
        - Session type: 
        - Gamescope version: 
        - Gamescope launch command(s): 
    render: markdown
  validations:
    required: false
- type: checkboxes
  id: backend
  attributes:
    label: Which gamescope backends have the issue you are reporting?
    description: You may select more than one.
    options:
      - label: Wayland (default for nested gamescope)
      - label: DRM (default for embedded gamescope, i.e. gamescope-session)
      - label: SDL
      - label: OpenVR
  validations:
    required: true
- type: textarea
  attributes:
    label: Logging, screenshots, or anything else
    description: |
      Please include any relevant logging, screenshots, or an `nvidia-bug-report.tar.gz` if applicable in this section.
      System reports generated by Steam (Help -> System Report on the desktop client or Settings -> System -> Create Report -> Save to Desktop in gamescope-session) can also be helpful.
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
