name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          ./scripts/install_arch_deps.sh
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build with gcc
        run: |
          export CC=gcc CXX=g++
          meson build-gcc/ --werror --auto-features=enabled
          ninja -C build-gcc/
      - name: Build with gcc (no vr)
        run: |
          export CC=gcc CXX=g++
          meson build-gcc-novr/ -Denable_openvr_support=false --werror --auto-features=enabled
          ninja -C build-gcc-novr/
      - name: Build with clang
        run: |
          export CC=clang CXX=clang++
          meson build-clang/ --werror --auto-features=enabled
          ninja -C build-clang/
