name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed git meson clang glslang libcap wlroots0.18 \
            sdl2 vulkan-headers libx11 libxmu libxcomposite libxrender libxres \
            libxtst libxkbcommon libdrm libinput wayland-protocols benchmark \
            xorg-xwayland pipewire cmake \
            libavif libheif aom rav1e libdecor libxdamage \
            luajit \
            catch2 gcovr
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Generate file list for formatting
        id: files
        run: |
          FILES=$(git ls-files src | grep -v -E '(reshade|shaders|\.o$|\.bin$|\.a$|\.so$|\.dylib$)')
          echo "formatted_files=$FILES" >> $GITHUB_OUTPUT
      - name: Format code with clang-format
        run: |
          echo "${{ steps.files.outputs.formatted_files }}" | xargs -P $(nproc) -- clang-format -i --
      - name: Commit formatted code
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "${{ steps.files.outputs.formatted_files }}" | xargs -r git add --
          git commit -m "chore: clang-format [skip ci]" || true
      - name: Build with gcc
        run: |
          export CC=gcc CXX=g++
          meson setup -Dinput_emulation=disabled --werror --auto-features=enabled -- build-gcc
          meson compile -C build-gcc
      - name: Build with gcc (no vr)
        run: |
          export CC=gcc CXX=g++
          meson setup -Dinput_emulation=disabled -Denable_openvr_support=false --werror --auto-features=enabled -- build-gcc-novr
          meson compile -C build-gcc-novr
      - name: Build with clang
        run: |
          export CC=clang CXX=clang++
          meson setup -Dinput_emulation=disabled --werror --auto-features=enabled -- build-clang
          meson compile -C build-clang
      - name: Build with clang (no vr)
        run: |
          export CC=clang CXX=clang++
          meson setup -Dinput_emulation=disabled -Denable_openvr_support=false --werror --auto-features=enabled -- build-clang-novr
          meson compile -C build-clang-novr
      - name: Run unit tests and collect coverage (gcc)
        run: |
          export CC=gcc CXX=g++
          meson configure -Db_coverage=true build-gcc
          meson test -C build-gcc --suite gamescope -v
          gcovr -f src --xml -o coverage-gcc.xml -s build-gcc
      - name: Run unit tests and collect coverage (clang)
        run: |
          export CC=clang CXX=clang++
          meson configure -Db_coverage=true build-clang
          meson test -C build-clang --suite gamescope -v
          gcovr -f src --xml -o coverage-clang.xml -s build-clang/ --gcov-executable="llvm-cov gcov"
      - name: Upload coverage report (gcc)
        uses: actions/upload-artifact@v7
        with:
          name: code coverage (gcc)
          path: coverage-gcc.xml
      - name: Upload coverage report (clang)
        uses: actions/upload-artifact@v7
        with:
          name: code coverage (clang)
          path: coverage-clang.xml
